version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MySQLpass48!
      MYSQL_DATABASE: golf_club_db
      MYSQL_USER: MySql_Test
      MYSQL_PASSWORD: MySQLpass48!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: